import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SidebarNav from "./(components)/SidebarNav";
import { cookies } from "next/headers";
import Modal from "./(components)/Modal";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AI Image Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies(); // Can only use in Server Components
  const token = cookieStore.get("access_token");

  const isLoggedIn = !!token; // Check if token is present

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Modal isOpen={!isLoggedIn} />
        <SidebarNav />
        {children}
      </body>
    </html>
  );
}
